**Program-9 **

Given the scores of students in 5 subjects, perform the following operations:

1) Create a 2D NumPy array with rows representing students and columns representing subjects.

2) Compute the total and average score of each student.

3) Find the highest scorer and the subject with the highest average score.

In [1]:
import numpy as np

# Step 1: Create a 2D NumPy array with rows as students and columns as subjects
scores = np.array([
    [85, 78, 92, 88, 76],  # Student 1
    [72, 84, 89, 91, 80],  # Student 2
    [89, 90, 94, 87, 88],  # Student 3
    [76, 85, 80, 83, 79],  # Student 4
    [90, 88, 85, 92, 91],  # Student 5
])


In [5]:
# Step 2: Compute the total and average score of each student
total_scores = np.sum(scores, axis=1)
average_scores = np.mean(scores, axis=1)


In [6]:
# Step 3: Find the highest scorer
highest_scorer_index = np.argmax(total_scores)
highest_scorer_total = total_scores[highest_scorer_index]



In [7]:
# Step 4: Find the subject with the highest average score
subject_averages = np.mean(scores, axis=0)
highest_avg_subject_index = np.argmax(subject_averages)
highest_avg_subject_score = subject_averages[highest_avg_subject_index]



In [8]:
# Output the results
print("Scores Matrix (Students x Subjects):\n", scores)
print("\nTotal Scores of Students:", total_scores)
print("Average Scores of Students:", average_scores)
print(f"\nHighest Scorer: Student {highest_scorer_index + 1} with Total Score {highest_scorer_total}")
print(
    f"Subject with Highest Average Score: Subject {highest_avg_subject_index + 1} "
    f"with Average Score {highest_avg_subject_score:.2f}"
)

Scores Matrix (Students x Subjects):
 [[85 78 92 88 76]
 [72 84 89 91 80]
 [89 90 94 87 88]
 [76 85 80 83 79]
 [90 88 85 92 91]]

Total Scores of Students: [419 416 448 403 446]
Average Scores of Students: [83.8 83.2 89.6 80.6 89.2]

Highest Scorer: Student 3 with Total Score 448
Subject with Highest Average Score: Subject 4 with Average Score 88.20
